version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dev_ancol
    container_name: d_ancol_web
    external_links:
      - dev_mysql:mysql
    networks:
      default:
        ipv4_address: 172.18.0.40
    volumes:
      - storage:/storage
      - ../_htdocs/net_ancol_web/:/app/
      - ./:/docker/
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml
    mem_limit: 1000m
    environment:
      VIRTUAL_HOST: "ancol.vm"
      VIRTUAL_PORT: "80"
      # PHP_XDEBUG_ENABLED: 1
      # PHP_IDE_CONFIG: serverName=ancol.vm
      # XDEBUG_CONFIG: remote_host=172.18.0.1 remote_connect_back=1

  prop:
    build:
      context: .
      dockerfile: Dockerfile
    image: dev_ancol
    container_name: d_ancol_prop
    external_links:
      - dev_mysql:mysql
    networks:
      default:
        ipv4_address: 172.18.0.41
    volumes:
      - storage:/storage
      - ../_htdocs/net_ancol_prop/:/app/
      - ./:/docker/
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml
    mem_limit: 1000m
    environment:
      VIRTUAL_HOST: "properti.ancol.vm"
      VIRTUAL_PORT: "80"
      # PHP_XDEBUG_ENABLED: 1
      # PHP_IDE_CONFIG: serverName=prop.ancol.vm
      # XDEBUG_CONFIG: remote_host=172.18.0.1 remote_connect_back=1

  corp:
    build:
      context: .
      dockerfile: Dockerfile
    image: dev_ancol
    container_name: d_ancol_corp
    external_links:
      - dev_mysql:mysql
    networks:
      default:
        ipv4_address: 172.18.0.42
    volumes:
      - storage:/storage
      - ../_htdocs/net_ancol_corp/:/app/
      - ./:/docker/
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml
    mem_limit: 1000m
    environment:
      VIRTUAL_HOST: "korporat.ancol.vm"
      VIRTUAL_PORT: "80"
      # PHP_XDEBUG_ENABLED: 1
      # PHP_IDE_CONFIG: serverName=ancol.vm
      # XDEBUG_CONFIG: remote_host=172.18.0.1 remote_connect_back=1

  html:
    image: jojomi/lighttpd-static:latest
    container_name: d_ancol_html
    volumes:
      - ../_htdocs/net_ancol_html:/var/www:ro
    mem_limit: 100m
    environment:
      VIRTUAL_HOST: "html.ancol.vm"
      VIRTUAL_PORT: "80"

  #######################################
  # Redis
  #######################################
  redis:
    image: redis:alpine
    container_name: d_ancol_redis
    networks:
      default:
        ipv4_address: 172.18.0.49
    volumes:
      - redis:/data
    mem_limit: 500m
    environment:
      VIRTUAL_HOST: "redis.ancol.vm"
      VIRTUAL_PORT: "80"

#######################################
# Storage
#######################################
volumes:
  storage:
    driver: local
    driver_opts:
      device: /home/ip310/Documents/dc_ancol/backup
      o: bind
  redis:
    driver: local
    driver_opts:
      device: /home/lxc/redis_ancol
      o: bind

networks:
  default:
    external:
      name: dev
